version: '2'
services:
  api_tuvoz:
    image: fjvigil/api_tuvoz
    user: root
    command: 'php artisan serve --host=0.0.0.0 --port=8080'
    restart: always             # run as a service
    ports:
      - 8080:8080
